cluster_name         = "my-private-eks-cluster"
vpc_cidr             = "13.0.0.0/16"
public_subnet_cidrs  = "13.0.1.0/24"
private_subnet_cidrs = ["13.0.2.0/24", "13.0.3.0/24"]
availability_zones   = ["ap-south-1a", "ap-south-1b"]
instance_type        = "t3.medium"
addons               = ["vpc-cni", "coredns", "kube-proxy"]
sg_protocol          = "tcp"
allow_all_route      = "0.0.0.0/0"
